//
//  AppStrings.swift
//  Jugnoo Driver
//
//  Created by cl-macmini-67 on 26/03/18.
//  Copyright © 2018 Socomo. All rights reserved.
//

import Foundation

struct AppStrings {
    static let Login = "LOGIN"
    static let Register = "REGISTER"
    static let Looking_For_Customer_App = "Looking for Customer App?"
    static let Driver_Application = "DRIVER APPLICATION"
    static let English = "English"
    static let Generate_Otp = "GENERATE OTP"
    static let Dont_have_an_driver_account = "Don’t have an driver account?"
    static let Register_Here = "Register Here"
    static let Phone_Number = "Phone Number"
    static let OTP_Desc = "Please enter your One Time Password sent to"
    static let OTP_placeholder = "Enter One Time Password"
    static let Resend_OTP = "Resend OTP"
    static let Submit = "SUBMIT"
    static let Or = "OR"
    static let Verification = "VERIFICATION"
    static let Register_As_Driver = "REGISTER AS DRIVER"
    static let Name = "Name"
    static let Referral_Code = "Referral Code"
    static let Select_City = "Select City"
    static let Select_Vehicle = "Select Vehicle"
    static let Vehicle_Status = "Vehicle Status"
    static let Select_Offering = "Select Offering"
    static let Already_have_a_driver_account = "Already have a driver account?"
    static let Login_Here = "Login Here"
    static let By_Signing_up_you_agree_to_our  = "By Signing up you agree to our"
    static let Terms_of_Use = "Terms of Use"
    static let Ok = "OK"
    static let Enter_Toll = "Enter Toll"
    static let Cancel = "Cancel"
    static let Please_enter_your_phonenumber = "Please enter your phone number"
    static let Select_vehicle_type = "Select vehicle type"
    static let CONTINUE = "CONTINUE"
    static let Please_enter_your_name = "Please enter your name"
    static let Do_you_want_to_make_call_to = "Do you want to make call to"
    static let deliveries_Accepted = "Deliveries Accepted"
    static let demoMessage = "Get a ride today for free with jugnoo and stand a chance to win iphone 6. Start referring now. T&C apply"
    static let demoDeliveryDate = "23 Mar, 2018   11:23 AM"
    static let notifications = "NOTIFICATIONS"
    static let messages = "Messages"
    static let tips_To_earn = "Tips To Earn"
    static let personalnfo = "Personal Info"
    static let bankDeails = "Bank Details"
    static let accountDeails = "Account Details"
    static let cardDeails = "Card Details"
    static let accNo = "Acc No. :"
    static let addAccount = "Add Account :"
    static let addCard = "ADD CARD"
    static let currentBalance = "Current Balance";
    static let ifsc = "IFSC :"
    static let bankName = "Bank Name :"
    static let bankLocation = "Bank Location"
    static let ride_history = "RIDE HISTORY"
    static let profile = "PROFILE"
    static let camera_denied_string = "This app does not have access to camera. You can enable access in Privacy Settings."
    static let Take_a_new_photo = "Take a new photo"
    static let Choose_from_existing = "Choose from existing"
    static let Device_has_no_camera = "Device has no camera."
    static let gallery_denied_string = "Access to photo library is denied. Please enable from setings."
    static let Upload_Documents = "Upload Documents"
    static let Mandatory = "Mandatory"
    static let Optional = "Optional"
    static let Required = "Required"
    static let Logout_Message = "Are you sure you want to logout?"
    static let Cancel_Ride = "Are you sure you want to cancel ride?"
    static let Delivery = "DELIVERY"
    static let Pool = "POOL"
    static let Something_went_wrong = "Something went wrong"
    static let noEntriesFound = "No entries found"
    static let noMessageToShow = "No Messages to show"
    static let noRidesToShow = "No Rides to show"
    static let Please_upload_required_documents = "Please upload required documents"
    static let unable_to_locate = "Unable to locate"
  static let End_Ride = "Are you sure you want to end ride?"
  static let Please_enter_a_reason = "Please enter a reason"
    static let please_enter_amount = "Please enter amount"
    static let please_enter_valide_card_number = "Please enter valide card number"
    static let please_enter_valid_expiry_date = "Please enter valide Expiry date"
    static let please_enter_valide_cvv_number = "Please enter valide CVV number"
    static let please_enter_valide_expiry_year = "Please enter valide Expiry Year"
    static let noCardAdded = "You do not have any card linked. Please add a card to add money to your wallet."
    static let wallet_detail = "WALLET DETAILS"
    static let card_detail = "CARD DETAILS"
    static let TERMS = "TERMS"
    static let i_disagree = "I DISAGREE"
    static let i_agree = "I AGREE"
    static let show_terms = "Show Terms"
    static let about = "ABOUT"
    static let FAQ = "FAQ"
    static let PRIVACY = "PRIVACY"
    static let FARE_DETAILS = "FARE_DETAILS"
    static let SCHEDULES_TNC = "SCHEDULES_TNC"
  static let Document_Authentication = "I accept that documents uploaded by me are true and correct. I understand that any attempt of providing incorrect, misleading information or fake documents will lead to my immediate black listing from the \(getBusinessName()) platform. \(getBusinessName()) platform reserves the right to take the matter to the law enforcement authorities in case of forged documents."
  static let Not_Operational = "Sorry! Currently we are not operational in your area"
  static let Call_Us = "Call Us"
  static let Get_Support_Call = "Get Support Call"
  static let Rate_Card = "Rate Card"
  static let Language_Preferences = "Language Preferences"
  static let Logout = "Logout"
  static let Support = "Support"
  
  static let Before_Ride = "Before Ride"
  static let Pickup_Charges_per_km = "Pickup Charges"
  static let Applicable_after = "Applicable after"
  static let In_Ride = "In Ride"
  static let Base_Fare = "Base Fare"
  static let Distance = "Distance"
  static let Time = "Time"
  static let per_km = "per km"
  static let per_min = "per min"
  static let Referral = "Referral"
  static let Driver_to_Customer = "Driver to Customer"
  static let Driver_to_Driver = "Driver to Driver"
  static let No_Rate_Card_available = "No Rate Card available"
  
  static let Download = "Download"
  
  static let Send_us_a_message = "Send us an email"
  
  static let Issue_Description = "Issue Description"
  static let Please_enter_issue_description = "Please enter issue description"
  static let Unable_to_send_mail_at_this_moment = "Unable to send mail at this moment"
  static let Get_Support_Call_Message = "Press the below button to get support from \(getBusinessName()). Our executive will call you shortly."
  static let Get_Call = "Get Call"
  
  static func getBusinessName() -> String {
    return "Jugnoo"
  }
  static let Please_press_submit_button = "Please press submit button"
  static let Jugnoo_Driver_Support = "\(getBusinessName()) Driver Support"
  static let Driver = "Driver"
  
  static let Upload = "Upload"
  static let Uploaded = "Uploaded"
  static let Rejected = "Rejected"
  static let Verified = "Verified"
  static let Approval_Pending = "Approval Pending"
  static let Upload_Again = "Upload Again"
  static let Rejection_Reason = "Rejection Reason"
  static let Invalid_Document = "Invalid Document"
  
  static let Language_Change_Confirmation = "Change language to"
  static let Proceed = "Proceed"
  
  static let Jugnoo_ON = "ON"
  static let Jugnoo_OFF = "OFF"
  static let Home = "Home"
  static let Earnings = "Earnings"
    static let Wallet = "Wallet"
  static let Super_Driver = "Super Drivers"
  static let TAKE_CASH = "TAKE CASH"
  static let Place_bid = "Place bid"
  static let Bid = "Bid"
static let Accept = "Accept"
  static let Estimated_Distance = "Estimated Distance"
 static let  Reduce = "Reduce"
 static let  by = "by"
static let Increase = "Increase"
 static let ARRIVING = "ARRIVING"
static let   ARRIVED = "ARRIVED"
static let START_RIDE = "START RIDE"
  static let END_RIDE = "END RIDE"
  static let CANCEL_RIDE = "CANCEL RIDE"
  static let SEND = "SEND"
static let ADD = "ADD"
static let  After = "After"
static let distance_charge_will_be = "distance charge will be"
    
    static let ride_over = "Ride Over"
    static let away = "away"
    static let showDropLocation = "Drop Location"
    static let hide = "Hide"
    static let rateYourCustomer = "Rate Your Customer"
    static let done = "DONE"
    static let checkRideSummary = "To check your ride summary visit earnings screen"
    static let RATING = "RATING"
  static let SHARE = "SHARE"
  
  static let InviteANDEarn = "Invite & Earn"
  static let Your_Referral_Code_is = "Your Referral Code is"
  static let  Please_enter_Customer_Phone_No =  "Please enter Customer Phone No."
  static let Phone_No = "Phone No."
  static let Earn = "Earn"
  static let Activity = "Activity"
  
  static let total_downloads = "No. of Downloads"
  static let total_rides_taken = "No. of First Rides Taken"
  static let Money_Earned_from_Referrals = "Money Earned from Referrals"
  static let Data_effective_from = "Data effective from"
  static let Driver_ID = "Driver ID"
  static let Rides_Taken = "Rides Taken"
  static let Rides_Missed = "Rides Missed"
  static let Rides_Cancelled = "Rides Cancelled"
  
  static let Monthly_Score = "Monthly Score"
  static let Your_Internet_Connection_Appears_To_Be_Offline = "Your Internet Connection Appears To Be Offline"
  static let Type_a_message = "Type a message"
  static let Call = "Call"
  static let Drop = "Drop"
  static let Location = "Location"

  
  static let Connect_with_Stripe = "Connect with Stripe"
  static let View_Stripe_account = "View Stripe account"
  
  static let TODAYS_EARNING  = "TODAY’S EARNING"
  static let WALLET_BALANCE = "WALLET BALANCE"
  static let DAY_WISE_BREAKUP = "DAY WISE BREAKUP"
  static let NEFT_PENDING = "NEFT PENDING"
  static let THIS_WEEK = "THIS WEEK"
  static let DAILY_EARNINGS = "DAILY EARNINGS"
  
  static let Bank_Deposit = "Bank Deposit"
  static let Cash_Collected = "Cash Collected"
  static let Your_Income = "Your Income"
  static let TOTAL_DISTANCE = "TOTAL DISTANCE"
  static let Trips = "Trips"
  static let Rides = "Rides"
  static let Deliveries = "Deliveries"
  static let Ride = "Ride"
  static let TRIP_EARNINGS = "TRIP EARNINGS"
  static let TRIP_DETAILS = "TRIP DETAILS"
   static let WAIT_TIME = "WAIT TIME"
 static let DURATION = "DURATION"
  static let How_to_Recharge = "How to Recharge"
  static let View_Wallet_Transactions = "View Wallet Transactions"
static let WAllET_TRANSACTIONS = "WALLET TRANSACTIONS"
  static let Added = "Added"
  static let Deducted = "Deducted"
  static let No_Data = "No Data"
  static let noTransactionsToShow = "No Transaction to show"
  static let Driver_Resources = "DRIVER RESOURCES"
  static let Driver_Resources_capitalized = "Driver Resources"
    static let aboutUs = "About"
    static let rateUs = "Rate us on App Store"
    static let likeUs = "Like us on Facebook"
    static let termsConditions = "Terms and Conditions"
    static let privacyPolicy = "Privacy Policy"
    static let whoWeAre = "Who are we?"
    static let arrived_Alert = "You must be present near the customer pickup location to mark ride arrived."
    static let daily = "Daily"
    static let weekly = "Weekly"
    static let superBiker = "Super Bikers"
  static let Cancelled = "Cancelled"
  static let INVOICE = "INVOICE"
  static let Enter_Referral_Code = "Enter referral code (Optional)"
  static let Referral_code = "Referral code"
  static let Waze_Enabled = "Waze Navigation"
  static let VEHICLE_INFORMATION = "VEHICLE INFORMATION"
  static let Make = "Make"
  static let Model = "Model"
  static let Color = "Color"
  static let Year = "Year"
  static let Number_of_Doors = "Number of Doors"
  static let Number_of_Seatbelts = "Number of Seatbelts"
  
  static let Please_enter_year = "Please enter year"
  static let Please_select_color = "Please select color"
  static let Please_select_model = "Please select model"
  static let Please_select_make_and_model_of_your_vehicle = "Please select make and model of your vehicle"
  static let Please_select_make = "Please select make"
  
  static let Driver_Agreement = "Driver Agreement"
  static let Debt = "Debt"
  static let Ringtone_Full_Volume_on_Incoming_Request = "Ringtone Full Volume on Incoming Request"
  static let Settings = "Settings"
  
  static let Please_select_number_of_doors = "Please select number of doors"
  static let Please_select_number_of_seatbelts = "Please select number of seatbelts"

  static let Add_Luggage = "ADD LUGGAGE"
  static let Fare_per_Baggage = "Fare per Baggage"
  static let Luggage_Charges = "Luggage Charges"
  static let Change = "CHANGE"

}


struct ParametersKeys {
    static let phone_no = "phone_no"
    static let country_code = "country_code"
    static let latitude = "latitude"
    static let longitude = "longitude"
    static let password = "password"
    
    
    static let user_name = "user_name"
    static let alt_phone_no = "alt_phone_no"
    static let city = "city"
    static let vehicle_type = "vehicle_type"
    static let offering_type = "offering_type"
    static let vehicle_status = "vehicle_status"
    static let device_type = "device_type"
    static let device_name = "device_name"
    static let app_version = "app_version"
    static let os_version = "os_version"
    static let country = "country"
    static let client_id = "client_id"
    static let login_type = "login_type"
    static let referral_code = "referral_code"
    static let device_token = "device_token"
    static let unique_device_id = "unique_device_id"
    static let device_rooted = "device_rooted"
    
    static let access_token = "access_token"
    static let locale = "locale"
    static let is_access_token_new = "is_access_token_new"
    static let imei = "imei"
    static let auto_n_cab_installed = "auto_n_cab_installed"
    static let uber_installed = "uber_installed"
    static let telerickshaw_installed = "telerickshaw_installed"
    static let ola_installed = "ola_installed"
    
    static let operator_token = "operator_token"
    static let updated_user_name = "user_name"
    
    static let login_documents = "login_documents"
    
    static let image = "image"
    static let doc_type_num = "doc_type_num"
    static let img_position = "img_position"
    
    static let offset = "offset"
    
    static let start_from = "start_from"
    static let engagement_date = "engagement_date"
    static let business_id = "business_id"
    static let flag = "flag"
  
  static let is_driver = "is_driver"
  
  static let updated_phone_no = "updated_phone_no"
  static let updated_country_code = "updated_country_code"
  static let verification_token = "verification_token"
  
  static let invoice_id = "invoice_id"
  
    static let drop_address = "drop_address"
    static let drop_latitude = "drop_latitude"
    static let drop_longitude = "drop_longitude"
    static let engagement_id = "engagement_id"
  static let redirect_uri = "redirect_uri"
  static let scope = "scope"
  static let response_type = "response_type"
  static let city_id = "city_id"
  
  static let model_id = "model_id"
  static let vehicle_make_id = "vehicle_make_id"
  static let vehicle_year = "vehicle_year"
  
   static let door_id = "door_id"
   static let seat_belt_id = "seat_belt_id"
   static let color_id = "color_id"
  static let vehicle_details = "vehicle_details"
  static let luggage_count = "luggage_count"
  
}

struct HardCodeValue {
    static let owned = "Owned"
}
